resources:
  - name: rtBuildGitRepo
    type: GitRepo
    configuration:
      gitProvider: vootla_git
      path: ChaitanyaVootla/jfrogMultiTest
      branches:
        include: main
pipelines:
  - name: rt_playground
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: docker_group
          dockerFileLocation: utils
          dockerFileName: Dockerfile
          dockerImageName: stg-repo.jfrog.info/testimages
          dockerImageTag: ${run_number}
          inputResources:
            - name: rtBuildGitRepo

      - name: docker_push
        type: Bash
        configuration:
          affinityGroup: docker_group
          integrations:
            - name: artVootla
          inputSteps:
            - name: docker_build
        execution:
          onExecute:
            - docker images
            - jfrog rt dp stg-repo.jfrog.info/testimages:${run_number} buildsplayground
