resources:
  - name: testTrigger
    type: GitRepo
    configuration:
      gitProvider: git
      path: ChaitanyaVootla/jfrogMultiTest
pipelines:
  - name: test_reports
    steps:
      - name: test_report
        type: Bash
        configuration:
          inputResources:
            - name: testTrigger
        execution:
          onExecute:
            - echo "<testsuite tests="3">
                  <testcase classname="foo1" name="ASuccessfulTest"/>
                  <testcase classname="foo2" name="AnotherSuccessfulTest"/>
                  <testcase classname="foo3" name="AFailingTest">
                      <failure type="NotEnoughFoo"> details about failure </failure>
                  </testcase>
                </testsuite>" > cache.txt
            - save_tests cache.txt
