resources:
  - name: testTrigger
    type: GitRepo
    configuration:
      gitProvider: git
      path: ChaitanyaVootla/jfrogMultiTest
pipelines:
  - name: test_reports
    steps:
      - name: test_report
        type: Bash
        configuration:
          inputResources:
            - name: testTrigger
        execution:
          onExecute:
            - echo "state=pipeline2" > cache.txt
            - save_tests cache.txt
