resources:
  - name: testTrigger
    type: GitRepo
    configuration:
      gitProvider: git
      path: ChaitanyaVootla/jfrogMultiTest
      environmentVariables:
        reportsCount: 10000
pipelines:
  - name: test_reports
    steps:
      - name: test_report
        type: Bash
        configuration:
          inputResources:
            - name: testTrigger
        execution:
          onExecute:
            - pushd $res_testTrigger_resourcePath
            - npm install
            - touch .env
            - echo "REPORTS_COUNT=$reportsCount" >> .env
            - npm run test
            - save_tests $res_testTrigger_resourcePath/junit.xml
      - name: no_test_reports
        type: Bash
        configuration:
          inputSteps:
            - name: test_report
        execution:
          onExecute:
            - echo "done"
