resources:
  - name: testTrigger
    type: GitRepo
    configuration:
      gitProvider: git
      path: ChaitanyaVootla/jfrogMultiTest
pipelines:
  - name: test_reports
    steps:
      - name: test_report
        type: Bash
        configuration:
          inputResources:
            - name: testTrigger
        execution:
          onExecute:
            - save_tests $res_testTrigger_resourcePath/utils/
      - name: no_test_reports_1
        type: Bash
        configuration:
          inputSteps:
            - name: test_report
        execution:
          onExecute:
            - echo "done"
      - name: no_test_reports_2
        type: Bash
        configuration:
          inputSteps:
            - name: test_report
        execution:
          onExecute:
            - echo "done"
