resources:
  - name: testTrigger
    type: GitRepo
    configuration:
      gitProvider: vootla_git
      path: ChaitanyaVootla/jfrogMultiTest
pipelines:
  - name: test_reports
    configuration:
      environmentVariables:
        readOnly:
          reportsCount: 100
          suitesCount: 100
    steps:
      - name: test_report
        type: Bash
        configuration:
          inputResources:
            - name: testTrigger
        execution:
          onExecute:
            - pushd $res_testTrigger_resourcePath
            - npm install
            - touch .env
            - echo "REPORTS_COUNT=$reportsCount" >> .env
            - echo "SUITES_COUNT=$suitesCount" >> .env
            - TOTAL_TESTS=$(($reportsCount*$suitesCount))
            # - update_run_description $TOTAL_TESTS
            - npm run test
            - save_tests $res_testTrigger_resourcePath/
      - name: no_test_reports
        type: Bash
        configuration:
          inputSteps:
            - name: test_report
        execution:
          onExecute:
            - echo "done"
